export const corporateClients: string[] = [
  "3M",
  "Titan",
  "TVS",
  "AstraZeneca",
  "Altran",
  "Apollo Hospitals",
  "Bosch",
  "Honeywell",
  "Himalaya",
  "GE",
  "IIM",
  "Jubilant FoodWorks",
  "Kansai Nerolac",
  "Manipal Hospitals",
  "Myntra",
  "Nissan",
  "Ola",
  "Schneider",
  "Siemens",
  "Societe Generale",
  "Tata Power",
  "Toyota",
  "Volvo",
  "Wipro",
  "XIME",
  "Wonderla",
];
