export type ClientCategory =
  | "All"
  | "Manufacturing & Industrial"
  | "Automotive & Mobility"
  | "Technology & IT"
  | "Healthcare & Pharmaceuticals"
  | "Energy & Infrastructure"
  | "Consumer & Retail"
  | "BFSI & Professional Services"
  | "Education & Academia";

export interface ClientItem {
  id: string;
  name: string;
  logo: string;
  category: Exclude<ClientCategory, "All">;
  featured?: boolean;
}

export const clientCategories: ClientCategory[] = [
  "All",
  "Automotive & Mobility",
  "Technology & IT",
  "Healthcare & Pharmaceuticals",
  "Manufacturing & Industrial",
  "Energy & Infrastructure",
  "Consumer & Retail",
  "BFSI & Professional Services",
  "Education & Academia",
];

// Master corporate client roster arranged in alphabetical order (A to Z)
export const clientRoster: ClientItem[] = [
  {
    id: "3m",
    name: "3M",
    logo: "/logos/clients/3m.png",
    category: "Manufacturing & Industrial",
    featured: true,
  },
  {
    id: "advinus",
    name: "Advinus Therapeutics",
    logo: "/logos/clients/advinus.png",
    category: "Healthcare & Pharmaceuticals",
  },
  {
    id: "airtel",
    name: "Airtel",
    logo: "/logos/clients/airtel.webp",
    category: "Technology & IT",
    featured: true,
  },
  {
    id: "akzonobel",
    name: "AkzoNobel",
    logo: "/logos/clients/akzonobel.jpg",
    category: "Manufacturing & Industrial",
  },
  {
    id: "alstom",
    name: "Alstom",
    logo: "/logos/clients/alstom-logo.png",
    category: "Manufacturing & Industrial",
    featured: true,
  },
  {
    id: "altran",
    name: "Altran",
    logo: "/logos/clients/altran.png",
    category: "Technology & IT",
  },
  {
    id: "anglo",
    name: "Anglo American",
    logo: "/logos/clients/anglo.png",
    category: "Manufacturing & Industrial",
  },
  {
    id: "apollo-hospitals",
    name: "Apollo Hospitals",
    logo: "/logos/clients/apollo.jpeg",
    category: "Healthcare & Pharmaceuticals",
    featured: true,
  },
  {
    id: "arm",
    name: "Arm",
    logo: "/logos/clients/arm.svg",
    category: "Technology & IT",
    featured: true,
  },
  {
    id: "astrazeneca",
    name: "AstraZeneca",
    logo: "/logos/clients/astra.jpeg",
    category: "Healthcare & Pharmaceuticals",
    featured: true,
  },
  {
    id: "beckon",
    name: "Beckon",
    logo: "/logos/clients/beckon.jpeg",
    category: "BFSI & Professional Services",
  },
  {
    id: "biocon",
    name: "Biocon",
    logo: "/logos/clients/biocon.jpg",
    category: "Healthcare & Pharmaceuticals",
    featured: true,
  },
  {
    id: "bonfiglioli",
    name: "Bonfiglioli",
    logo: "/logos/clients/bonfiglioli.webp",
    category: "Manufacturing & Industrial",
  },
  {
    id: "bosch",
    name: "Bosch",
    logo: "/logos/clients/bosch.png",
    category: "Automotive & Mobility",
    featured: true,
  },
  {
    id: "brilliant-printers",
    name: "Brilliant Printers",
    logo: "/logos/clients/brilliant-printers.jpeg",
    category: "Manufacturing & Industrial",
  },
  {
    id: "cades",
    name: "Cades Digitech",
    logo: "/logos/clients/cades.png",
    category: "Technology & IT",
  },
  {
    id: "carbon-clean",
    name: "Carbon Clean",
    logo: "/logos/clients/carbon.png",
    category: "Energy & Infrastructure",
  },
  {
    id: "cgi",
    name: "CGI",
    logo: "/logos/clients/cgi.jpeg",
    category: "Technology & IT",
    featured: true,
  },
  {
    id: "danieli",
    name: "Danieli",
    logo: "/logos/clients/danieli.png",
    category: "Manufacturing & Industrial",
  },
  {
    id: "digitech",
    name: "Digitech",
    logo: "/logos/clients/digitech.png",
    category: "Technology & IT",
  },
  {
    id: "eaton",
    name: "Eaton",
    logo: "/logos/clients/eaton.jpg",
    category: "Manufacturing & Industrial",
    featured: true,
  },
  {
    id: "echidna",
    name: "Echidna",
    logo: "/logos/clients/echidna.jpeg",
    category: "Technology & IT",
  },
  {
    id: "epic",
    name: "Epic Systems",
    logo: "/logos/clients/epic.png",
    category: "Technology & IT",
  },
  {
    id: "esco",
    name: "ESCO",
    logo: "/logos/clients/esco.png",
    category: "Manufacturing & Industrial",
  },
  {
    id: "federal-mogul",
    name: "Federal-Mogul Goetze",
    logo: "/logos/clients/federal-mogul-goetze.png",
    category: "Automotive & Mobility",
  },
  {
    id: "flex",
    name: "Flex",
    logo: "/logos/clients/flex.png",
    category: "Technology & IT",
    featured: true,
  },
  {
    id: "flowserve",
    name: "Flowserve",
    logo: "/logos/clients/flowserve.png",
    category: "Manufacturing & Industrial",
  },
  {
    id: "ge",
    name: "General Electric (GE)",
    logo: "/logos/clients/ge.jpg",
    category: "Manufacturing & Industrial",
    featured: true,
  },
  {
    id: "himalaya",
    name: "Himalaya Wellness",
    logo: "/logos/clients/himalaya.jpg",
    category: "Consumer & Retail",
    featured: true,
  },
  {
    id: "himatsingka",
    name: "Himatsingka",
    logo: "/logos/clients/himatsingka.png",
    category: "Manufacturing & Industrial",
  },
  {
    id: "honeywell",
    name: "Honeywell",
    logo: "/logos/clients/honeywell.png",
    category: "Technology & IT",
    featured: true,
  },
  {
    id: "hotel-oberoi",
    name: "Hotel Oberoi",
    logo: "/logos/clients/hotel-oberoi.jpeg",
    category: "Consumer & Retail",
  },
  {
    id: "iim",
    name: "IIM (Indian Institute of Management)",
    logo: "/logos/clients/iim.jpg",
    category: "Education & Academia",
    featured: true,
  },
  {
    id: "infant-travels",
    name: "Infant Travels",
    logo: "/logos/clients/infant-travels.png",
    category: "BFSI & Professional Services",
  },
  {
    id: "infinite-computers",
    name: "Infinite Computer Solutions",
    logo: "/logos/clients/infinite-computers.png",
    category: "Technology & IT",
  },
  {
    id: "jubilant-foodworks",
    name: "Jubilant FoodWorks",
    logo: "/logos/clients/jubilant-foodworks.svg",
    category: "Consumer & Retail",
    featured: true,
  },
  {
    id: "kansai-nerolac",
    name: "Kansai Nerolac",
    logo: "/logos/clients/kansai-nerolac.jpg",
    category: "Manufacturing & Industrial",
    featured: true,
  },
  {
    id: "kemwell",
    name: "Kemwell Biopharma",
    logo: "/logos/clients/kemwell-pharma.jpeg",
    category: "Healthcare & Pharmaceuticals",
  },
  {
    id: "kennametal",
    name: "Kennametal",
    logo: "/logos/clients/kennametal.jpg",
    category: "Manufacturing & Industrial",
  },
  {
    id: "konspec",
    name: "Konspec",
    logo: "/logos/clients/konspec.jpeg",
    category: "Manufacturing & Industrial",
  },
  {
    id: "kyocera",
    name: "Kyocera",
    logo: "/logos/clients/kyocera.png",
    category: "Technology & IT",
  },
  {
    id: "larsen-and-toubro",
    name: "Larsen & Toubro",
    logo: "/logos/clients/larsen-and-toubro.png",
    category: "Energy & Infrastructure",
    featured: true,
  },
  {
    id: "logix",
    name: "Logix Infosecurity",
    logo: "/logos/clients/logix.jpg",
    category: "Technology & IT",
  },
  {
    id: "makino",
    name: "Makino",
    logo: "/logos/clients/makino.svg",
    category: "Manufacturing & Industrial",
  },
  {
    id: "manipal-hospitals",
    name: "Manipal Hospitals",
    logo: "/logos/clients/manipal-hospitals.png",
    category: "Healthcare & Pharmaceuticals",
    featured: true,
  },
  {
    id: "myntra",
    name: "Myntra",
    logo: "/logos/clients/myntra.png",
    category: "Consumer & Retail",
    featured: true,
  },
  {
    id: "natural-search",
    name: "Natural Search",
    logo: "/logos/clients/natural-search.jpeg",
    category: "Technology & IT",
  },
  {
    id: "nissan-motors",
    name: "Nissan Motors",
    logo: "/logos/clients/nissan-motors.jpeg",
    category: "Automotive & Mobility",
    featured: true,
  },
  {
    id: "ola",
    name: "Ola",
    logo: "/logos/clients/ola.png",
    category: "Automotive & Mobility",
    featured: true,
  },
  {
    id: "orchid-pharma",
    name: "Orchid Pharma",
    logo: "/logos/clients/orchid-pharma.jpg",
    category: "Healthcare & Pharmaceuticals",
  },
  {
    id: "otis",
    name: "OTIS Elevator Company",
    logo: "/logos/clients/otis.png",
    category: "Manufacturing & Industrial",
    featured: true,
  },
  {
    id: "polaris",
    name: "Polaris Financial Technology",
    logo: "/logos/clients/polaris.jpg",
    category: "BFSI & Professional Services",
  },
  {
    id: "print-point",
    name: "Print Point",
    logo: "/logos/clients/print-point.png",
    category: "Manufacturing & Industrial",
  },
  {
    id: "professional-services",
    name: "Professional Services Group",
    logo: "/logos/clients/professional-services.jpeg",
    category: "BFSI & Professional Services",
  },
  {
    id: "quintiles",
    name: "Quintiles (IQVIA)",
    logo: "/logos/clients/quintles.png",
    category: "Healthcare & Pharmaceuticals",
  },
  {
    id: "renault-nissan",
    name: "Renault Nissan",
    logo: "/logos/clients/renault-nissan.jpeg",
    category: "Automotive & Mobility",
    featured: true,
  },
  {
    id: "sahana-exports",
    name: "Sahana Exports",
    logo: "/logos/clients/sahana-exports.jpg",
    category: "Manufacturing & Industrial",
  },
  {
    id: "schneider-electric",
    name: "Schneider Electric",
    logo: "/logos/clients/schneider.png",
    category: "Energy & Infrastructure",
    featured: true,
  },
  {
    id: "sibm",
    name: "SIBM (Symbiosis Institute)",
    logo: "/logos/clients/sibm.png",
    category: "Education & Academia",
    featured: true,
  },
  {
    id: "siemens",
    name: "Siemens",
    logo: "/logos/clients/siemens.png",
    category: "Manufacturing & Industrial",
    featured: true,
  },
  {
    id: "societe-generale",
    name: "Societe Generale",
    logo: "/logos/clients/societe-generale.png",
    category: "BFSI & Professional Services",
    featured: true,
  },
  {
    id: "st-johns",
    name: "St. John's Hospital",
    logo: "/logos/clients/st-johns-hospital.png",
    category: "Healthcare & Pharmaceuticals",
  },
  {
    id: "strides",
    name: "Strides Pharma",
    logo: "/logos/clients/strides.png",
    category: "Healthcare & Pharmaceuticals",
  },
  {
    id: "swagelok",
    name: "Swagelok",
    logo: "/logos/clients/siemens-swagelok.png",
    category: "Manufacturing & Industrial",
  },
  {
    id: "swiss-re",
    name: "Swiss Re",
    logo: "/logos/clients/swiss-re.png",
    category: "BFSI & Professional Services",
    featured: true,
  },
  {
    id: "syngene",
    name: "Syngene International",
    logo: "/logos/clients/syngene.png",
    category: "Healthcare & Pharmaceuticals",
    featured: true,
  },
  {
    id: "tafe",
    name: "TAFE (Tractors and Farm Equipment)",
    logo: "/logos/clients/tafe.svg",
    category: "Automotive & Mobility",
  },
  {
    id: "tata-bp-solar",
    name: "Tata BP Solar",
    logo: "/logos/clients/tata-bp-solar.png",
    category: "Energy & Infrastructure",
  },
  {
    id: "tata-power",
    name: "Tata Power",
    logo: "/logos/clients/tata-power.svg",
    category: "Energy & Infrastructure",
    featured: true,
  },
  {
    id: "td-power",
    name: "TD Power Systems",
    logo: "/logos/clients/td-power.png",
    category: "Energy & Infrastructure",
  },
  {
    id: "terex",
    name: "TEREX",
    logo: "/logos/clients/terex.png",
    category: "Manufacturing & Industrial",
  },
  {
    id: "the-practice",
    name: "The Practice",
    logo: "/logos/clients/the-practice.jpg",
    category: "BFSI & Professional Services",
  },
  {
    id: "timken",
    name: "TIMKEN",
    logo: "/logos/clients/timken.png",
    category: "Manufacturing & Industrial",
    featured: true,
  },
  {
    id: "titan-company",
    name: "Titan Company",
    logo: "/logos/clients/titan-watches.jpg",
    category: "Consumer & Retail",
    featured: true,
  },
  {
    id: "toyota",
    name: "Toyota Group",
    logo: "/logos/clients/toyota-group.png",
    category: "Automotive & Mobility",
    featured: true,
  },
  {
    id: "trident-hyundai",
    name: "Trident Hyundai",
    logo: "/logos/clients/trident-hyundai.jpeg",
    category: "Automotive & Mobility",
  },
  {
    id: "tvs-motors",
    name: "TVS Motor Company",
    logo: "/logos/clients/tvs-motors.png",
    category: "Automotive & Mobility",
    featured: true,
  },
  {
    id: "tvs-tyres",
    name: "TVS Tyres",
    logo: "/logos/clients/tvs-tyres.png",
    category: "Automotive & Mobility",
  },
  {
    id: "united-breweries",
    name: "United Breweries",
    logo: "/logos/clients/united-breweries.jpg",
    category: "Consumer & Retail",
    featured: true,
  },
  {
    id: "united-spirits",
    name: "United Spirits",
    logo: "/logos/clients/united-spirits.jpeg",
    category: "Consumer & Retail",
  },
  {
    id: "volvo",
    name: "Volvo Group",
    logo: "/logos/clients/volvo.png",
    category: "Automotive & Mobility",
    featured: true,
  },
  {
    id: "waters",
    name: "Waters Corporation",
    logo: "/logos/clients/waters.jpeg",
    category: "Healthcare & Pharmaceuticals",
  },
  {
    id: "wipro",
    name: "Wipro",
    logo: "/logos/clients/wipro.jpeg",
    category: "Technology & IT",
    featured: true,
  },
  {
    id: "wonderla",
    name: "Wonderla Holidays",
    logo: "/logos/clients/wonderla.png",
    category: "Consumer & Retail",
    featured: true,
  },
  {
    id: "xime",
    name: "XIME (Xavier Institute of Management)",
    logo: "/logos/clients/xime.png",
    category: "Education & Academia",
    featured: true,
  },
  {
    id: "yashomati",
    name: "Yashomati Hospital",
    logo: "/logos/clients/yashomati-hospital.png",
    category: "Healthcare & Pharmaceuticals",
  },
  {
    id: "yuno-packaging",
    name: "Yuno Packaging",
    logo: "/logos/clients/yuno-packaging.png",
    category: "Manufacturing & Industrial",
  },
  {
    id: "zuari-cement",
    name: "Zuari Cement",
    logo: "/logos/clients/zuari-cements.png",
    category: "Energy & Infrastructure",
  },
];

// Backward-compatibility export for existing components, also in alphabetical order
export const corporateClients: string[] = clientRoster.map((c) => c.name);
